FROM oracle/oraclelinux
MAINTAINER Ilver Anache <ilver.anache@gmail.com>

ADD /home/sample_wls1213_generic_response /resources
ADD /home/wls1213_infrastructure_generic.jar /resources

# Paso 2: Instalar Oracle WebLogic