FROM oracle/oraclelinux
MAINTAINER Ilver Anache <ilver.anache@gmail.com>

ADD ./assets/. /resources
#ADD /vagrant_data/weblogic. /resources
#COPY ../../sample_wls1213_generic_response /
#COPY ../../wls1213_infrastructure_generic.jar /

# Paso 2: Instalar Oracle WebLogic
