FROM oracle/oraclelinux
MAINTAINER Ilver Anache <ilver.anache@gmail.com>

ADD /vagrant_data/weblogic/sample_wls1213_generic_response /resources
ADD /vagrant_data/weblogic/wls1213_infrastructure_generic.jar /resources

# Paso 2: Instalar Oracle WebLogic
